language: python
python:
  - "3.6"
  - "3.8"
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/tests
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - pytest tests/