language: python
python:
  - "3.6"
  - "3.8"

branches:
  only:
    - master
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/tests
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pytest --cov=analytical_validation tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: validawaree-backend
  on:
    branch: master

